### ISSUE TITLE
Launch script fails to work often

### ISSUE THREAD

**Issue by mathuin** [xeger/kos-ramp#25]
When I use `launch_asc.ks` to get a relatively normal rocket to orbit, maybe seven times out of eight it fails to follow the launch-turn-circularize pattern.  The problem appears to be the apoapsis not quite reaching the target value, stopping at around 199,900 meters for a 200,000 meter launch.

I'm tinkering with potential fixes and will submit a pull request if I get anything reliable.

**Comment by fellipec** [comment]
Curious. I had made hundreds of launchs to make sure this works.
When reaching near the desired apo altitude it throttle down the engines to avoid overshoot so depending of your rocket its expected that it took some time to reach the desired apo.
Looks I fail to realize some scenario. Im curious too see this

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mathuin** [comment]
When I comment out the throttling code, the launches that previously failed stop failing.  I'm wondering about that equation.  Would it help to have craft files?

**Comment by xeger** [comment]
I encountered something similar, where the throttle got so low that the ship took forever to reach the target apoapsis. I added a 0.05 fudge factor which is sloppy, but seemed to work. On master, the ascent code now contains:
```
return 1.05 - min(1,max(0,ApoCompensation)).
```

Let me know if that fixes things. (Happy to entertain better fixes, too!)

**Comment by mathuin** [comment]
This fix works!  It also appears to be more precise than an uncompensated throttle -- my burn faults on flights without RCS are 0.2 m/s instead of 0.4+ m/s which is nice.
