### ISSUE TITLE
KSP/kOS new versions

### ISSUE THREAD

**Issue by fellipec** [xeger/kos-ramp#41]
Back from few months busy. 
I installed KSP 1.4.3 and latest kOS. Noticed the RCS fine tune part and the curves of atm autopilot are doing exactly the opposite of what they used to do. Wondering if that has something to do with newer versions of KSP/kOS.

**Comment by astappiev** [comment]
I close this issue as it was created a few years ago. Feel free to create a new one, if needed, and I will try to help.
